### ISSUE TITLE
Broker nerede :)

### ISSUE THREAD

**Issue by hinthorozu** [Fcakiroglu16/UdemyMicroservices#1]
Hocam selam eğitiminizi izliyordum ama benim için broker kısmı var diye ümit ederek aldım ama yok içerisinde göremedim var mı?

**Comment by Fcakiroglu16** [comment]
Merhaba, Broker olarak rabbitmq'ü kullanıyoruz. rabbitMQ kullanmak için  masstransit kütüphanesinden faydalanıyoruz.
